### ISSUE TITLE
no_data_thresh vs default_histogram

### ISSUE THREAD

**Issue by KMarkert** [Servir-Mekong/hydra-floods#17]
As discussed in #11 and #16, there are two solutions to provide a fallback for the thresholding algorithms to succeed when little/no data meet the algorithm parameters. This little to no data issue usually happens when there is a large amount of masked data in the image or the no data in the image meet the `initial_threshold` criteria (little/no water).  Here we can discuss the advantages/disadvantages to both approaches and figure out which path (or both) we would like to include in the package.

#### `no_data_thresh`
a simple if statements on the EE server side that will always threshold data given the no data threshold value.
_Pros:_ 
1. simple
2. intuitive for users

_Cons:_ 
1. Computationally expensive if used
2. may not provide best results as the threshold is more of a lower bound vs best case

#### `default_histogram` 
a more sophisticated way to handle the missing data issue where a histogram is always provided and used if the algorithms cannot sample a histogram based on the issues described above.
_Pros:_ 
1. fits better with the algorithm structure
2. Will yield better results (given the default histogram is realistic)
3. No if statements needed

_Cons:_ 
1. Not intuitive for most users to create a histogram to fallback on

**Comment by ArjenHaag** [comment]
Quick update as mentioned in last call. I tried to get the 'best of both worlds' by constructing a histogram from the user-defined **`no_data_thresh`** which will always return that threshold when fed into Otsu. For example, when setting it at -16:

![image](https://user-images.githubusercontent.com/7656091/113702061-500c8700-96d9-11eb-9985-abaa15399ba9.png)

Here's a code link with this implemented (keeps timing out today, not sure why, it worked yesterday, will check later): https://code.earthengine.google.com/44a25876e60b80d80522990d5094174d

But I am not sure if this is so much more efficient than the `ee.Algorithms.If` statement we're using now. I always thought that it was very inefficient because it will always execute both true and false cases, but in our case the false case does not execute anything, it only assigns a single numerical value to a variable. So perhaps the extra overhead of pre-generating a histogram and filtering the histogram FeatureCollection is even less efficient than this?

@KMarkert Also not sure if this is exactly what you meant, as you stated "Will yield better results (given the default histogram is realistic)" and this is not realistic at all.
