### ISSUE TITLE
Attribute Error in Getting Started Chapter

### ISSUE THREAD

**Issue by mickymags** [Servir-Mekong/hydra-floods#33]
Again this is running on Google Colab, Python 3.7.12. 

I'll attempt this section in a local jupyter notebook soon to see if anything changes. 

This error occurs in the final code block of the "Getting Started" Chapter of the HF Documentation, under the Machine Learning Heading. 

The code block appears as follows: 

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#add bands for features used in RF model
s1_features = s1.apply_func(hf.add_indices, ["vv_vh_ratio", "ndpi"])

#scale the bands using the scaling_dict
s1_norm = s1_features.apply_func(
    ml.standard_image_scaling,
    scaling_dict=scaling_dict,
    feature_names=feature_names
)

#apply the prediction on the dataset
predicted = s1_norm.apply_func(lambda x: x.classify(rf))

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Running this code returns an Attribute Error on Line 5 of the code (the line starting with 's1_norm'), stating the following: 

"Attribute Error: 'NoneType' object has no attribute 'apply func'. "

Thanks in advance.

**Comment by KMarkert** [comment]
Whoops, looks like my change from #30 had a syntax error. The `s1_features` is throwing an error is later processing because the expression to set the variable has a syntax error which runs but returns `None`. The expression to assign it should be `s1_features = s1.apply_func(hf.add_indices, indices=["vv_vh_ratio", "ndpi"])`

I will fix the documentation to be correct but this raises a more important issue where the `.apply_func()` method fails silently and should be more explicit if the syntax isn't correct. Will open a new issue to fix that.

**Comment by mickymags** [comment]
It is now working with the expression you suggested. Thanks!

**Comment by KMarkert** [comment]
Documentation is fixed with 69f93ec6b1cea7c80b7ba77fd12c16bfc46793c2
