### ISSUE TITLE
Documentation and general feedback

### ISSUE THREAD

**Issue by aaraney** [Servir-Mekong/hydra-floods#8]
First off, you have some great stuff here! I stumbled into your project helping a colleague of mine get up to speed with Docker and how to use it with your what you've provided. It's fantastic to see another project utilizing GEE's python API.

In skimming through the docs and repo in my free time, I have a few suggestions and just general questions from one dev to another.

As for suggestions:
1. As someone who has also decimated Docker language to scientists, I share the struggle with you. Docker image, Dockerfiles, Docker containers... to a new user this kind of language can be daunting and there is definitely a language barrier. I think some of the language in the `Installation` section of the `README` could be improved for scientists sake. Namely, 
> docker run -it \
  -v ~/<PROJECT-DIR>/:/mnt/<PROJECT-DIR> \
  --name hydrafloods_container kmarkert/hydrafloods

might be more intuitive to a new comer using if the full option names were used. For example:
> docker run --interactive --tty \
  --volume ~/<PROJECT-DIR>/:/mnt/<PROJECT-DIR> \
  --name hydrafloods_container kmarkert/hydrafloods

However, I think the section right after the docker code snipped does a great job at conveying the desired meaning. Thoughts?

Alternatively, it might be even simpler to provide a simple CLI using `Click` or `argparse` that uses the `Docker` python API to spin up the container instead. I am thinking the user would `pip install hydrafloods.cli` (You could use a namespace package to just install a part of the library) then the user interfaces using the `hydrafloods` command. For example `hydrafloods --volume .` could be the equivalent to the above command. This could also be nice if you wanted to allow a user to provide a python script as an `entrypoint` instead of having an interactive session (i.e. `hydrafloods example.py`). It might be a little wonky with the earth engine oauth requirements, but it isn't impossible. As of now, earth engine is just saving credentials to `~/.config/earthengine/credentials`.

2. I think a little added context in `Example` wouldn't hurt. In the first line of the example code itself including a line comment like `# content of example.py` could help clarify that the example is a python script and isn't to be copy and pasted to the shell. 

3. I'm not always great about this myself -- so I will try not to be a hypocrite, but a few added docstrings wouldn't hurt in the code itself. Class docstrings and method docstring in particular. Making this an open issue might not be a bad idea either. Id be happy to contribute some myself in my free time!

4. First, thanks for having a contribution guide! This is something a lot of projects lack (myself included). It would be helpful if you could specify which docstring style you expect and what code testing suite you expect tests are written in. Personally, I'd love to contribute some docstring and add some tests, but I don't want my time to be misplaced you know?

Questions:
Well really -- just question. Just curious why you went with MkDocs? I have used it in the past and I love how easy it is and that it supports Markdown -- so much easier to start with than restructure text IMO. I saw an API Reference section, just out of curiosity do you plan to use a plugin to auto build docs from docstrings or what is your plan? Iv'e switched over to Sphinx myself, but admittedly it is a little more daunting to new comers which might turn them away (unfortunately).

This is an awesome project and I am stoked to hear your direction.

**Comment by KMarkert** [comment]
Hi @aaraney 👋 thanks a lot for your comments and thoughts! This is really exciting that you are willing to contribute and help out, I will try my best to make contributing as easy for you as possible.

Here are my reponses:

1. I agree with you, it took me a while to get up to speed on using docker but once I figured it out, I was (and still am) sold on using docker. The idea was once a stable version is available then it will be easy to deploy without worrying about dependencies.
I have updated the installation guides per your suggestion to include the full names of the docker arguments (224b782). 
I agree that there should be some CLI availability to support users running it directly without having to start the docker in interactive mode. I have experience with writing CLI with Python (using [Fire](https://google.github.io/python-fire/guide/), I find it more concise than argparse) and would like to expose these commands in the Docker Image but I haven't gotten to that yet. If you have experience in this, I would be happy to see a PR for something.

2. I agree with you that adding more context into the example code is helpful. I went through this example with colleagues in my office and we had the same confusion so something must have been wrong! 😆 
I have updated the example script per your suggestion (b9ac4a7)

3. This is a general problem with the package, poor in line documentation. I think documentation in code is really important but the poor docs was due to tight deadlines...
Please feel free to open an issue to move the discussion there.

4. Thanks, I always find it helpful when open source projects have a contributing guide so I try to do the same, so good to know it is appreciated!
I personally prefer the [Google Style Python Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) and if you were to contribute documentation please use this format. I will update the contributing guide to mention this code style and others (I have been using snake case for variables and functions/methods and camel case for objects).

I used to use Sphinx for my doc build but have since switched to MkDocs purely due to ease of use. I find that MkDocs has a quicker develop time, less headache when getting things to work, and I really like the material theme. I have not tried this yet but have it on my todo (after writing docstrings) to try the [mkdocstrings](https://github.com/pawamoy/mkdocstrings) package to build docs with the api info. If you would like to open a new issue to discuss if this works and get it implemented on the auto doc build workflow.

Again, happy to have you on board to contribute!  😁
